apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wbk7azg3j-nodejs
  janus-idp.io/tekton: wbk7azg3j-nodejs
  backstage.io/kubernetes-id: wbk7azg3j-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wbk7azg3j-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
